backend:
  name: github
  repo: CampusFS/site-CFS

media_folder: static/assets/images
public_folder: assets/images
logo_url: https://peaceful-johnson-580335.netlify.com/assets/logo/CFS.png
site_url: https://peaceful-johnson-580335.netlify.com
display_url: https://peaceful-johnson-580335.netlify.com

slug:
  encoding: ascii
  clean_accents: true

collections:
#  Actualités
- name: news
  label: Actualité
  folder: src/content/news
  create: true
  slug: "{{date}}_{{slug}}"
  fields:
  - { name: "type", widget: "hidden", label: "Type", default: "news" }
  - { name: date, label: Date de publication, widget: date, format: "YYYY-MM-DD" }
  - { name: image, label: Image, widget: image, required: false, hint: "Cette image apparaîtra directement sur la page d'accueil." }
  - { name: priority, label: Actualité principale, widget: boolean, hint: "Si activé, l'actualité apparaîtra dans le carrousel de l'en-tête de la page d'accueil.", required: false}
  - { name: title, label: Titre, pattern: ["^.{0,80}$", "Le titre ne doit pas excéder 80 caractères."] }
  - { name: summary,
      label: Résumé,
      hint: "Ce texte apparaitra en tant que résumé de l'actualité dans la listes des actualités sur la page d'accueil. Les sauts de ligne ne sont pas pris en compte.",
      widget: text,
      pattern: ["^(.|\\s){0,300}$", "Le résumé ne doit pas excéder 300 caractères."],
      required: false}
  - { name: body,
      label: Description,
      widget: markdown,
      buttons: ['bold', 'italic', 'link', 'heading-one', 'heading-two', 'quote', 'bulleted-list', 'numbered-list']}


# Pages
- label: Pages
  name: pages
  files:
  #Page d'accueil : encadré descriptif du CFS
  - label: Description du CFS
    description: "Contenu de l'encadré sur la page d'accueil décrivant succintement le CFS."
    name: descriptionCFS
    file: src/content/pages/descriptionCFS.md
    fields:
    - { name: "type", widget: "hidden", label: "Type", default: "descriptionCFS" }
    - { name: title,
        label: "Titre",
        hint: "Mettre entre double asterisques la partie du titre à colorer. Ex : **Texte à colorer**",
        pattern: ["^.{0,50}$", "Le titre ne doit pas excéder 50 caractères."],
    }
    - { name: body,
        label: Corps,
        widget: text,
        pattern: ["^(.|\\s){0,700}$", "Le résumé ne doit pas excéder 700 caractères."],
        required: false
    }
    - { name: hideStats,
        label: Cacher les chiffres,
        widget: boolean,
        hint: "Si activé, la partie \"En chiffres\" de l'encart ne sera pas affiché",
        default: false,
        required: false
    }
    - {
      name: schoolPartners,
      label: Établissement partenaires,
      widget: number,
      default: 0,
      min: 0,
      valueType: int,
      hint: "Indiquer '0' si vous ne souhaitez pas afficher cette statistique."
    }
    - {
      name: formationsNumber,
      label: Formations,
      widget: number,
      default: 0,
      min: 0,
      valueType: int,
      hint: "Indiquer '0' si vous ne souhaitez pas afficher cette statistique."
    }
    - {
      name: companyPartners,
      label:  Entreprises participantes,
      widget: number,
      default: 0,
      min: 0,
      valueType: int,
      hint: "Indiquer '0' si vous ne souhaitez pas afficher cette statistique."
    }
